name: Publish
on: [push]
concurrency: ci-${{ github.ref }}
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/wrapper-validation-action@v1

      # Generate the build number based on tags to allow per branch build numbers, not something github provides by default.
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.ref }}

      - run: ./gradlew build javadocJar checkVersion publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          BRANCH_NAME: ${{ github.ref }}
